### ISSUE TITLE
DatBoi fails after starting: `Callback was already called.`

### ISSUE THREAD

**Issue by garbados** [garbados/dat-boi#13]
The callback I get back reliably looks like this:

```
Error: Callback was already called.
    at /root/dat-boi/node_modules/async/dist/async.js:955:32
    at queryDone (/root/dat-boi/node_modules/discovery-channel/index.js:148:5)
    at Object.done [as callback] (/root/dat-boi/node_modules/k-rpc/index.js:135:21)
    at UTP.onmessage (/root/dat-boi/node_modules/k-rpc-socket/index.js:118:11)
    at emitTwo (events.js:130:20)
    at UTP.emit (events.js:213:7)
    at UTP._onmessage (/root/dat-boi/node_modules/utp-native/index.js:70:8)
```

This stack trace gives me nothing useful. I am not sure why it is occurring. This issue will track its resolution.

**Comment by garbados** [comment]
I've updated DatBoi to use a fork of discovery-channel until I figure out wtf is actually going on.
